### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Kefta** [PHPApple/Vistio#1]
I can't open the menu

**Comment by PHPApple** [comment]
Try turning it off and back on again.

**Comment by Liam-MacKay** [comment]
this is definitely a clientside thing. you need to have adobe reader fully installed and updated. you also may have a ram deficiency, which you can fix by [downloading more ram](www.downloadmoreram.com)

**Comment by James-Parsons** [comment]
t0 add to wh4t @Liam-MacKay s4id br0wsing with  g00gl3 u1tr0n (ultronbrowser.info)
