### ISSUE TITLE
( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by James-Parsons** [PHPApple/Vistio#4]
h3110 m80, th1s d4nk issu3 weel addr3ss th3 issu3 of s3cur1ty on ur d4nk CoD s3v3r

**Comment by James-Parsons** [comment]
lel m9 as i h4v3 s33n n0 r3p1y t0 thi$ issu3, i must assum3 the3 w0rst and r3p0rt this r3p0 as h4x. yu wi11 b3 bann3d fr0m xbox 1iv3 fursher.

**Comment by PHPApple** [comment]
Your issue is that you have not downloaded enough RAM. You must download some more ram in order to successfully use this software.

**Comment by James-Parsons** [comment]
lel m8 i alr3ady h4v3 420 p3t4byt3s 0f R4M i ev3n am running g00gl3 u1tr0n m8 wh4t els3 d0 i n33d

**Comment by Liam-MacKay** [comment]
Dick Cheney made money off the iraq war
